name: kurve # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Remake of the classic game "Achtung, die Kurve!" # 79 char long summary
description: |
  Remake of the classic game "Achtung, die Kurve!"

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  kurve:
    command: 
    plugs:
      - opengl
      - x11
      - desktop
      - desktop-legacy
      - unity7
      - home

parts:
  kurve:
    plugin: cmake
    build-snaps: [cmake/latest/edge]
    source: https://github.com/h-valdes/kurve
    source-type: git
    source-depth: 1
    stage-packages:
    - libglu1-mesa
    - libfreetype6
    - libglfw3
    - libpng16-16
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    build-packages:
    - libglfw3-dev
    - libfreetype-dev
    - nlohmann-json3-dev
    override-build: |
      mkdir Release
      cd Release
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
      make install
