name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb
        sudo apt install -y libglfw3-dev libfreetype-dev nlohmann-json3-dev

    - name: Make and run the library in Release mode
      env:
        DISPLAY: ":99.0" 
      run: |
        mkdir Release
        cd Release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make install
        kurve
        
    - name: Make and run the library in Debug mode
      env:
        DISPLAY: ":99.0" 
      run: |
        mkdir Debug
        cd Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
        ./kurve