name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install libglfw3-dev
        sudo apt install libfreetype-dev
        sudo apt install nlohmann-json3-dev
        
    - name: Make and run the library in Release mode
      run: |
        mkdir Release
        cd Release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make install
        kurve
        
    - name: Make and run the library in Debug mode
      run: |
        mkdir Debug
        cd Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
        ./kurve